on: [push, pull_request]
defaults:
  run:
    shell: bash
jobs:
  build-sdist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - run: python -m venv .venv
      - run: .venv/bin/pip install build
      - run: .venv/bin/python -m build --sdist
      - uses: actions/upload-artifact@v3
        with:
          name: sdist
          path: dist/videojitter-*.tar.gz
          if-no-files-found: error
  build-wheel:
    runs-on: ubuntu-latest
    needs: build-sdist
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: sdist
      - run: tar --gzip --extract --verbose --strip-components=1 --file videojitter-*.tar.gz
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - run: python -m venv .venv
      - run: .venv/bin/pip install build
      - run: .venv/bin/python -m build --wheel
      - uses: actions/upload-artifact@v3
        with:
          name: wheel
          path: dist/videojitter-*.whl
          if-no-files-found: error
  sigstore:
    runs-on: ubuntu-latest
    needs:
      - build-sdist
      - build-wheel
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: sdist
      - uses: actions/download-artifact@v3
        with:
          name: wheel
      - uses: sigstore/gh-action-sigstore-python@v2.1.0
        with:
          inputs: "*"
      - uses: actions/upload-artifact@v3
        with:
          name: sigstore
          path: "*.sigstore"
          if-no-files-found: error
  release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/videojitter-')
    needs:
      - build-sdist
      - build-wheel
      - sigstore
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: sdist
      - uses: actions/download-artifact@v3
        with:
          name: wheel
      - uses: actions/download-artifact@v3
        with:
          name: sigstore
      - uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: "*"
          generate_release_notes: true
