on:
  release:
    types: [released]
jobs:
  pypi:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/project/videojitter/
    permissions:
      id-token: write
    steps:
      - uses: dsaltares/fetch-gh-release-asset@1.1.1
        with:
          file: '.+\.(tar\.gz|whl)'
          regex: true
          version: ${{ github.event.release.id }}
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          verbose: true
          print-hash: true
          packages-dir: .
